Migration to Angular 15
OntimizeWeb/ontimize-web-ngx-filemanager pull request #115
Opened 2023-07-21 05:52 UTC by patricia-martinez-imatia

2023-10-04 08:55 UTC, tomfacal approved these changes

2023-10-06 06:55 UTC, daniel-grana requested changes

2023-10-06 06:55 UTC, daniel-grana commented on projects/ontimize-web-ngx-filemanager/package.json
> +    "ontimize-web-ngx": "ontimize-web-ngx-15.0.0-SNAPSHOT-2"
Change this version with beta.0

2023-10-06 07:04 UTC, tomfacal approved these changes

2023-10-06 07:04 UTC, daniel-grana approved these changes

2023-10-06 07:09 UTC, merged